config/routes.rb
Rails.application.routes.draw do
  root                 to: 'pages#home'
  get    '/blog',      to: 'products#blog'
  get    '/signup',    to: 'users#new'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'
  get    '/list',      to:  'products#show'
  resources :users,  except: [:new]
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :title,   presence: true, uniqueness: true
  validates :link,    presence: true, uniqueness: true
  validates :user_id, presence: true
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  before_save {self.email = email.downcase }
  validates :username,  presence: true, length: { minimum: 3, maximum: 50 },
                        uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,     presence: true, format: { with: VALID_EMAIL_REGEX },
                        uniqueness: true
  validates :telephone, presence: true
  validates :address,   presence: true
  validates :city,      presence: true
  has_secure_password
  validates :password,  presence: true, length:{ minimum: 6, maximum: 30 }

  def User.digest(string)
    cost = ActiveRecord::SecurePassword.min.cost ? BCrypt::Engine::MIN_COST :
                                                   BCrypt::Engine.cost
    BCrypt::password.create( string, cost: cost )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if logged_in?
      redirect_to blog_path
    else
    redirect_to login_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_params, only: [ :edit, :update, :destroy]
  before_action :require_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :require_same_user, only:[:edit, :update, :destroy]
  def index
    @products = Product.all
  end

  def show
    @products = Product.all
    @product =  Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = User.first
    if @product.save
      flash[:success] = "IPTV uploaded successsfully"
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:info] = "You link successfully updated"
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    if @product.destroy
      flash[:danger] = "IPTV successfully deleted"
      redirect_to products_path
    end
  end

  def blog
  end

  private

  def product_params
    params.require(:product).permit(:title, :link)
  end

  def set_params
    @product = Product.find(params[:id])
  end

  def require_same_user
    if current_user != @product.user && !current_user.admin?
      flash[:danger] = "You can only whatch iptv"
      redirect_to product_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Welcome guest"
      log_in user
      redirect_to blog_path
    else
      flash[:danger] = "You must be logged in to watch our channels"
      render 'new'
    end
  end

  def destroy
    log_out
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only:[:show, :edit, :update]
  before_action :login_same_user, only: [:index, :show, :edit, :update, :new]
  before_action :require_user, only:[:index, :show, :edit, :update, :new]
  before_action :login_admin, only: [:destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to you company"
      redirect_to users_path(current_user.admin?)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:info] = "You profile now updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:danger] = "User now removed"
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :telephone, :address, :city, :password, :password_confrimation)
  end

  def set_params
    @user = User.find(params[:id])
  end

  def login_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "Only your account"
      redirect_to user_path(current_user)
    end
  end

  def login_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin "
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    basic_title = "IPTV"
    if page_title.empty?
      basic_title
    else
      page_title + ' | ' + basic_title
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session[:user_id] = nil
    redirect_to root_path
  end

  def require_user
    unless  logged_in?
      flash[:danger] = "You must be loggeed in?"
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 80)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?=s#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/layouts/_nav.html.erb
<div class="head">
<% if logged_in? && current_user.admin? %>
  <%= link_to 'Create new client', signup_path, class: "btn btn-outline-secondary" %>
  <%= link_to 'Create new IPTV', new_product_path, class: "btn btn-outline-secondary" %>
  <%= link_to 'All Users', users_path, class: "btn btn-outline-secondary" %>
  <%= link_to 'All IPTV', products_path, class: "btn btn-outline-secondary"%>

  <%= link_to 'Logout', logout_path, method: :delete, class: "btn btn-outline-secondary float-right" %>
  <%= link_to 'My Profile', user_path(current_user), class: "btn btn-outline-secondary float-right" %>
<% elsif logged_in? %>
  <%= link_to 'Logout', logout_path, method: :delete, class: "btn btn-outline-secondary float-right" %>
<% end %>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= full_title(yield(:title))%></title>
    <link rel = "icon" href =
        "https://media.indiedb.com/images/games/1/51/50676/moon-transparent.png"
        type = "image/x-icon">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'shared/flash' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/products/_form.html.erb
<div id="all">
  <%= form_for @product do |p|%>
    <%= render 'shared/errors', obj: @product %>
    <div class="form-group">
      <label for="inputAddress2">Title</label>
      <%= p.text_field :title, class: "form-control"%>
    </div>
    <div class="form-group">
      <label for="inputAddress2">Link</label>
      <%= p.text_field :link, class: "form-control"%>
    </div>
      <br>
    <%= p.submit "Post", class: "btn btn-primary btn-lg btn-block" %>
  <% end %>
</div>

app/views/products/blog.html.erb
<%provide(:title, "MOON IPTV")%>
<img src="https://media.indiedb.com/images/games/1/51/50676/moon-transparent.png" id="home"  width="200px" height="200px">
<h1 class="home">Welcome to MOON IPTV</h1>
  <p class="clock">
    <%= Time.now %>
  </p>
<% if logged_in? %>
  <div class="ct">
    <%= link_to product_path(current_user) do %>
      <img id="tv" src="https://img.icons8.com/pastel-glyph/64/000000/tv.png" width="120px" height="120px">
    <% end %>
    <%= link_to user_path(current_user) do %>
      <img id="tv" src="https://img.icons8.com/ios-filled/50/000000/checked-user-male.png" width="120px" height="120px">
    <% end %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<%= render 'products/form' %>

app/views/products/index.html.erb
<%= provide(:title, "Home") %>
<h1 align="center" class="font-weight-bold">all IPTV </h1>
<br>
<% if logged_in? && current_user.admin? %>
  <div class="row row-cols-1 row-cols-md-3">
    <% @products.each do |product| %>
      <div class="col mb-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title"><%= product.title %></h2>
          </div>
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= link_to 'View', product_path(product), class: "btn btn-success"%>
            <%= link_to 'Edit', edit_product_path(product) , class:"btn btn-warning"%>
            <%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: "Are you sure? "}, class:"btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/products/new.html.erb
<%= provide(:title, "New IPTV") %>
<h1 align="center" class="font-weight-bold">Create new IPTV </h1>
<%= render 'products/form' %>

app/views/products/show.html.erb
<div class="card-deck">
  <div class="card">
    <div class="card-body">
      <video class="vd" width="650px" height="450px"  controls>
        <source src="<%= @product.link %>" >
      </video>
    </div>
  </div>
</div>
<div class="tas">
  <% @products.each do |product| %>
    <ul class="list-group">
      <li class="list-group-item"><%= link_to product.title, product_path(product) %></li>
    </ul>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">You have in total: <%= pluralize(obj.errors.count, "errors") %></h4>
    <hr>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type%>"> <%= message%></div>
<% end %>

app/views/users/_form.html.erb
<div id="all">
  <%= form_for @user do |u|%>
  <%= render 'shared/errors', obj: @user%>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputUsername4">Username</label>
        <%= u.text_field :username, class: "form-control"%>
      </div>
      <div class="form-group col-md-6">
        <label for="inputEmail4">Email</label>
        <%= u.email_field :email, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <label for="inputAddress2">Phone</label>
      <%= u.telephone_field :telephone, class: "form-control"%>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputEmail4">Address</label>
        <%= u.text_field :address, class: "form-control", placeholder: "Karpos, Partizanska"%>
      </div>
      <div class="form-group col-md-6">
        <label for="inputCity">City</label>
        <%= u.text_field :city, class: "form-control", placeholder: "Skopje, Kumanovo"%>
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword">Password</label>
      <%= u.password_field :password, class: "form-control"%>
    </div>
    <div class="form-group">
      <label for="inputAddress2">Confirmation Password </label>
      <%= u.password_field :password_confirmation, class: "form-control"%>
    </div>
    <br/>
    <%= u.submit "Accept", class:"btn btn-primary btn-lg btn-block" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= provide(:title, "Edit Profile") %>
<h1 align="center" class="font-weight-bold">Edit Profile</h1>
<%= render 'users/form' %>

app/views/users/index.html.erb
<%= provide(:title, "Users")%>

<div class="row row-cols-1 row-cols-md-3">
  <% @users.each do |user| %>
    <div class="col mb-4">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title"><%= user.username %></h2>
          <p class="card-text"><%= user.email%></p>
          <p class="card-text"><%= user.telephone%></p>
        </div>
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to 'View', user_path(user), class:"btn btn-info" %>
          <%= link_to 'Edit', edit_user_path(user) , class:"btn btn-warning"%>
          <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure? "}, class:"btn btn-danger" %>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= provide(:title, "Sign Up")%>
<h1 align="center" class="font-weight-bold">Sign Up</h1>
  <%= render 'users/form'%>

app/views/users/show.html.erb
<% provide(:title, @user.username)%>
<div id="all1">
  <div class="card"  style="width: 19rem;">
    <%= gravatar_for @user %>
    <div class="card-body">
      <h5 class="card-title"><%= @user.username %></h5>
    </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Email: <%= @user.email %></li>
        <li class="list-group-item">Phone: <%= @user.telephone %></li>
        <li class="list-group-item">Address: <%= @user.address %></li>
        <li class="list-group-item">City: <%= @user.city %></li>
      </ul>
    <div class="card-body">
      <%= link_to 'Back to IPTV', product_path, class:"btn btn-success"%>
      <%= link_to 'Edit', edit_user_path(current_user), class:"btn btn-info" %>
      <% if logged_in? && current_user.admin? %>
        <%= link_to 'Delete', user_path, method: :delete, data: {confirm: "Are you sure? "}, class:"btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>